### ISSUE TITLE
class_missing vs method dispatch

### ISSUE THREAD

**Issue by jonthegeek** [RConsortium/S7#372] opened 2023-10-02 17:13 UTC
I expected this to work:

``` r
# pak::pkg_install("RConsortium/S7") # Use latest dev build.
library(S7)

my_fun <- new_generic("my_fun", dispatch_args = "x")
method(my_fun, class_missing | NULL) <- function(x) {
  "In the method."
}

my_fun()
#> [1] "In the method."
my_fun(NULL)
#> [1] "In the method."
my_fun(class_missing)
#> Error: Can't find method for `my_fun(S3<S7_missing>)`.
```

<sup>Created on 2023-10-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Context: I have `as_class_a()` functions for class_a that go beyond its constructor, and I wanted to use them in the constructor of class_b (which has class_a as a property). I was surprised to see that calling them without an argument triggers an error, rather than being handled by the missing/NULL method.

Adding `new_S3_class("S7_missing")` to the method's dispatch union makes it work as expected:

``` r
method(my_fun, class_missing | NULL | new_S3_class("S7_missing")) <- function(x) {
  "In the method."
}

my_fun(class_missing)
#> [1] "In the method."
```

<sup>Created on 2023-10-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by hadley** [comment] 2023-10-02 20:21
You don't supply `class_missing` to the call; you just leave the argument missing:

``` r
library(S7)

my_fun <- new_generic("my_fun", dispatch_args = "x")
method(my_fun, class_missing | NULL) <- function(x) {
  "In the method."
}

my_fun()
#> [1] "In the method."
my_fun(NULL)
#> [1] "In the method."
my_fun()
#> [1] "In the method."
```

<sup>Created on 2023-10-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by hadley** [comment] 2023-10-02 20:21
Or is this a duplicate of #356?

**Comment by jonthegeek** [comment] 2023-10-02 20:33
I think it's probably related to #356. Actually that's almost definitely it; I thought I was supposed to supply `class_missing` like in the default constructor, but I'm guessing this will go away if I build my constructor more like a normal function (like I now see in the [Constructors section of the vignette](https://rconsortium.github.io/S7/articles/classes-objects.html#constructors)).

Let me try some experiments, one moment.

**Comment by jonthegeek** [comment] 2023-10-02 20:48
Ok, I was doing that because of a different issue... which I'm having trouble tracking down for a reprex. Hopefully either I'll squash it or open a new issue shortly. I think this particularly issue can be considered a duplicate/confusion related to #356.

**Closed** 2023-10-04 02:31 UTC
