### ISSUE TITLE
Cannot create a property when class is not defined

### ISSUE THREAD

**Issue by dipterix** [RConsortium/S7#417] opened 2024-08-04 07:08 UTC
I can imaging many cases where a property is the instance of the class itself,  or has cyclic deps:

``` r
directory <- S7::new_class(
  name = "directory",
  properties = S7::new_property(
    class = S7::new_union(NULL, directory)
  )
)
#> Error in eval(expr, envir, enclos): object 'directory' not found
```

<sup>Created on 2024-08-04 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

Can we have functions like `S7::new_promise_property` so the class only checks the existence of the class definition when instantiated?

**Comment by hadley** [comment] 2024-08-04 12:11
Duplicate of #250

**Closed by hadley** 2024-08-04 12:11 UTC

**Comment by dipterix** [comment] 2024-08-04 18:13
Nice! Thank you!
